name: Deploy MyST / Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main
      - master

# Permissions to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies & Jupyter Book
        run: |
          pip install "jupyter-book<2.0.0" trafilatura pandas ipykernel

      - name: Build Jupyter Book
        run: |
          jupyter-book build Notebooks

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Notebooks/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
